import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const profile = JSON.parse(readFileSync(resolve(root, "midnight/version-profile.json"), "utf8"));
const sourceNames = ["TmixAsset", "RandomnessThreshold", "YieldAdapter", "PrizePool"];
const sourcePaths = sourceNames.map((name) => resolve(root, `midnight/${name}.compact`));
const managedRoot = resolve(root, "midnight/managed");
const infoPaths = sourceNames.map((name) => resolve(managedRoot, name.replace(/[A-Z]/g, (letter, index) => `${index ? "-" : ""}${letter.toLowerCase()}`), "compiler/contract-info.json"));
const sourceMarkers = ["Shroudly", "supply cap", "threshold-only", "simulated-yield", "Disclosure Cohort", "claimNullifier", "deployerActive"];
const missingSources = sourcePaths.filter((path) => !existsSync(path));
const infos = infoPaths.filter((path) => existsSync(path)).map((path) => JSON.parse(readFileSync(path, "utf8")));
const allSources = sourcePaths.map((path) => readFileSync(path, "utf8")).join("\n");
const missingMarkers = sourceMarkers.filter((marker) => !allSources.toLowerCase().includes(marker.toLowerCase()));
const compiler = spawnSync("compact", ["compile", "--version"], { cwd: root, encoding: "utf8" });
const runtime = spawnSync("compact", ["compile", "--runtime-version"], { cwd: root, encoding: "utf8" });
const language = spawnSync("compact", ["compile", "--language-version"], { cwd: root, encoding: "utf8" });
const installedCompiler = (compiler.stdout ?? "").trim();
const installedRuntime = (runtime.stdout ?? "").trim();
const installedLanguage = (language.stdout ?? "").trim();
const artifactHashes = sourcePaths.filter((path) => existsSync(path)).map((path) => createHash("sha256").update(readFileSync(path)).digest("hex"));
const compactCompile = missingSources.length === 0 && infos.length === sourceNames.length && infos.every((info) => info["compiler-version"] === profile.compactCompiler && info["runtime-version"] === profile.compactRuntime);
const zkKeysGenerated = infoPaths.every((path) => existsSync(resolve(path, "..", "..", "keys")) && readdirSync(resolve(path, "..", "..", "keys")).length > 0);
const compatibilityMatch = installedCompiler === profile.compactCompiler && installedRuntime === profile.compactRuntime && installedLanguage === profile.compactLanguage;
const gates = { ...profile.gates, compactCompile, zkKeysGenerated, compatibilityMatch };
const result = { profile: profile.profile, expected: { compiler: profile.compactCompiler, runtime: profile.compactRuntime, language: profile.compactLanguage }, installed: { compiler: installedCompiler, runtime: installedRuntime, language: installedLanguage }, contracts: sourceNames.map((name, index) => ({ name, source: sourcePaths[index].replace(`${root}/`, ""), artifact: existsSync(infoPaths[index]) })), artifactHashes, sourceMarkers: missingMarkers.length === 0 ? "complete" : missingMarkers, gates, readyForPreprod: Object.entries(gates).filter(([key]) => key !== "mainnetTransactionsEnabled").every(([, value]) => Boolean(value)) };
console.log(JSON.stringify(result, null, 2));
if (missingSources.length || missingMarkers.length || !compactCompile || installedCompiler !== profile.compactCompiler || installedRuntime !== profile.compactRuntime) process.exitCode = 1;
if (process.argv.includes("--gate") && !result.readyForPreprod) process.exitCode = 1;
