#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=16

REPO_ROOT="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd -- "$REPO_ROOT"
REPO_SLUG="${GITHUB_REPOSITORY:-}"
if [[ -z "$REPO_SLUG" ]]; then
  REPO_SLUG="$(git config --get remote.origin.url 2>/dev/null | sed -E 's#^(https://github.com/|git@github.com:)##; s#\.git$##')"
fi
if [[ ! "$REPO_SLUG" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
  warn "could not derive a GitHub repository slug from GITHUB_REPOSITORY or remote.origin.url"
  exit 1
fi
REPO_URL="https://github.com/$REPO_SLUG"

require_value() {
  local key="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$key is required; stopping before an incomplete configuration is used"
    exit 1
  fi
}

require_https() {
  local key="$1" value="$2"
  require_value "$key" "$value"
  if [[ "$value" != https://* ]]; then
    warn "$key must use HTTPS"
    exit 1
  fi
}

require_hash() {
  local key="$1" value="$2"
  require_value "$key" "$value"
  if [[ ! "$value" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
    warn "$key must be a 0x-prefixed 32-byte artifact hash"
    exit 1
  fi
}

banner "Shroudly Preprod human-gate wizard"
note "For a local production-style file, run with ENV_FILE=.env.production.local. The default .env is ignored by git."
note "This wizard never asks for wallet keys, deployer keys, provider passwords, or service-role credentials."

stage "Resolve the Compact compatibility gate"
say "The current release requires the compatibility decision tracked in issue #3."
open_url "$REPO_URL/issues/3"
open_url "https://docs.midnight.network/relnotes/support-matrix"
step "Review the checked-in feasibility report and the support matrix with the maintainer."
step "Verify the corrected profile: Compact CLI 0.5.2, language 0.23.0, compiler 0.31.1, and runtime 0.16.0. The CLI version and language version are distinct; do not treat CLI 0.5.2 as a language version."
step "Only continue after issue #3 has an explicit accepted profile or a reviewed compatibility update. Do not deploy contracts against an unresolved profile."
pause "After the maintainer has resolved issue #3, press Enter"
if ! confirm "Is issue #3 resolved and the pinned Compatibility Profile approved for this Preprod qualification?"; then
  warn "Compatibility is unresolved; stopping before provider configuration."
  exit 1
fi

stage "Create provider accounts and recovery controls"
say "Create the isolated control-plane accounts required by the runbook."
open_url "$REPO_URL/settings"
open_url "https://vercel.com/new"
open_url "https://dashboard.render.com/"
open_url "https://supabase.com/dashboard"
open_url "https://resend.com/domains"
open_url "https://betterstack.com/"
step "Verify personal GitHub repository access plus Vercel, Render, Supabase, Resend, and Better Stack ownership."
step "Enable phishing-resistant MFA where supported; otherwise use a unique authenticator factor and keep recovery codes offline. Do not use shared mailboxes or shared browsers."
step "Re-check current provider limits, pricing, retention, authentication, and billing terms at provisioning time. The wizard records no plan assumption."
pause "After account ownership, MFA, and billing/recovery controls are ready, press Enter"
if ! confirm "Are the provider accounts isolated, MFA-protected, and backed by an offline recovery path?"; then
  warn "Provider account controls are not confirmed; stopping."
  exit 1
fi

stage "Provision isolated Preprod wallets and authorities"
say "Create and fund the wallet and authority set without exposing private material."
open_url "https://docs.midnight.network/relnotes/support-matrix"
open_url "https://docs.midnight.network/api-reference/dapp-connector"
open_url "https://docs.midnight.network/guides/dust-sponsorship"
step "Create five isolated participant wallets, then separate deployer, 2-of-3 governance, emergency, randomness, and DUST accounts."
step "Fund the required accounts on Midnight Preprod only. These are valueless, resettable test assets; do not use Mainnet."
step "Record only wallet labels and public addresses in the protected release worksheet. Keep seeds, signing keys, Recovery Kits, and contributor credentials offline or in their designated provider secret store."
pause "After all required wallets and authority labels are ready, press Enter"
if ! confirm "Are the five participant wallets and separate authorities funded and recorded without private keys entering this wizard?"; then
  warn "Wallet/authority provisioning is not confirmed; stopping."
  exit 1
fi

stage "Deploy the four Preprod contracts and seed the reserve"
say "Use the reviewed protected deployment workflow for the pinned Midnight toolchain."
open_url "$REPO_URL/issues/18"
open_url "https://docs.midnight.network/relnotes/support-matrix"
warn "The repository does not provide a human-safe one-line deployment command. Use the reviewed procedure in docs/operations/runbook.md and the protected deployment environment; do not invent a command or paste a key here."
step 'Run the reviewed preflight `pnpm midnight:compile:keys` followed by `pnpm midnight:profile`; require all four artifacts, expected prover/verifier pairs, and the approved Compatibility Profile facts to match before entering deployment.'
step "Deploy the four contracts, pin their dependency/artifact inputs, and call the one-shot TmixAsset.seedPrizeReserve(PrizePool) circuit with the separate reserve authority before any faucet or fixture allocation. Never use deployer minting for qualification."
step "After reserve seeding is finalized, use only the bounded TmixAsset allocation circuit for the isolated evidence fixture; issuance is expected to remain locked until reserve seeding succeeds."
step "For each transaction, verify network finality, indexer visibility, and a fresh ledger read before treating it as successful."
step "Record the immutable deployment ID, four public contract IDs, and four 0x-prefixed artifact hashes in the protected release worksheet. Stage 9 will capture only those public values for local/Vercel config."
pause "After the reviewed deployment and reserve-seeding workflow has produced finalized outputs, press Enter"
if ! confirm "Are all four contracts finalized on Preprod, the reserve/fixture seeded safely, and the public IDs/hashes recorded?"; then
  warn "Contract deployment is not confirmed; stopping."
  exit 1
fi

stage "Apply Supabase Backup Accounts controls"
say "Configure the operational data store before enabling Backup Accounts."
open_url "https://supabase.com/dashboard"
open_url "https://supabase.com/docs/guides/deployment/database-migrations"
open_url "https://supabase.com/docs/guides/database/postgres/row-level-security"
open_url "https://supabase.com/docs/guides/auth/auth-mfa"
step "Apply supabase/migrations/20260915000000_backup_accounts.sql before creating or restoring Backup Accounts."
step "Verify grants and RLS for anon and authenticated users, and verify that backup read/delete operations require the intended AAL2 session. Test deny paths as well as allow paths."
step "Configure Auth, backup/retention settings, and any provider billing required by the runbook. Keep Supabase service-role material server-side only."
note "No SUPABASE_URL, SUPABASE_ANON_KEY, service-role key, backup ciphertext, or user data is captured or written by this wizard. Enter those directly into the approved server-side deployment store if the deployed service requires them."
pause "After the migration, Auth, RLS, retention, and deny-path checks pass, press Enter"
if ! confirm "Is Supabase ready for Backup Accounts with the required RLS and AAL2 controls?"; then
  warn "Supabase controls are not confirmed; stopping."
  exit 1
fi

stage "Authenticate the Resend domain"
say "Set up the authentication-mail domain and record only the sender address."
open_url "https://resend.com/domains"
open_url "https://resend.com/docs/dashboard/domains/introduction"
step "Add a domain you own in Resend and publish the exact SPF and DKIM records it provides."
step "Publish DMARC at the chosen policy for this Preprod service, then wait for Resend verification. Do not treat an unverified domain as ready."
step "Choose the server-side authentication-mail sender address from the verified domain."
note "Captured value: RESEND_FROM. Source: the verified Resend domain configuration. Destination: ENV_FILE only; copy it manually to the approved server-side service configuration if needed. It is not a VITE value or a GitHub secret."
ask RESEND_FROM "Paste the exact authentication-mail sender address:"
require_value RESEND_FROM "$RESEND_FROM"
write_env RESEND_FROM "$RESEND_FROM"
pause "After Resend reports the domain and sender as verified, press Enter"
if ! confirm "Is the Resend Authentication Domain verified with SPF, DKIM, DMARC, and a working sender?"; then
  warn "Resend is not confirmed; stopping."
  exit 1
fi

stage "Deploy Sponsor Service and the randomness signer on Render"
say "Create isolated Render services and capture only their public HTTPS endpoints."
open_url "https://dashboard.render.com/"
open_url "https://render.com/docs/health-checks"
open_url "https://render.com/docs/configure-environment-variables"
step "Create the Sponsor Service and the on-demand randomness signer as isolated Render services. Configure the Sponsor Service health check as GET /healthz and keep service boundaries and access controls aligned with the runbook."
step "Inject signer/service credentials directly into Render's secret store. The wizard must never receive deployer keys, service-role keys, provider passwords, or contributor seeds."
note "Captured value: VITE_SHROUDLY_SPONSOR_URL. Source: the deployed Sponsor Service's public URL. Destination: ENV_FILE now and Vercel's public environment-variable set in Stage 9."
ask VITE_SHROUDLY_SPONSOR_URL "Paste the public Sponsor Service URL:"
require_https VITE_SHROUDLY_SPONSOR_URL "$VITE_SHROUDLY_SPONSOR_URL"
write_env VITE_SHROUDLY_SPONSOR_URL "$VITE_SHROUDLY_SPONSOR_URL"
note "Captured value: SHROUDLY_RENDER_AUTOMATION_ENDPOINT. Source: the approved Render automation/signer endpoint. Destination: ENV_FILE only for the isolated Render contributor runner; it is public routing, not a credential."
ask SHROUDLY_RENDER_AUTOMATION_ENDPOINT "Paste the Render automation endpoint:"
require_https SHROUDLY_RENDER_AUTOMATION_ENDPOINT "$SHROUDLY_RENDER_AUTOMATION_ENDPOINT"
write_env SHROUDLY_RENDER_AUTOMATION_ENDPOINT "$SHROUDLY_RENDER_AUTOMATION_ENDPOINT"
pause "After both Render services are healthy and their access controls are applied, press Enter"
if ! confirm "Are Sponsor Service and the randomness signer healthy, isolated, and using provider-side credentials?"; then
  warn "Render services are not confirmed; stopping."
  exit 1
fi

stage "Create the Better Stack heartbeat"
say "Create the five-minute operational heartbeat used by the Preprod health workflow."
open_url "https://betterstack.com/"
open_url "https://betterstack.com/docs/uptime/cron-and-heartbeat-monitor/"
step "Create a heartbeat with a five-minute expectation and the grace/escalation policy from docs/operations/runbook.md."
step "Copy the secret heartbeat URL from the heartbeat detail page. Treat it as a secret URL; never paste it into VITE config, an issue, a log, or evidence."
note "Captured value: BETTER_STACK_HEARTBEAT_URL. Source: Better Stack's heartbeat detail page. Destination: ENV_FILE now and the GitHub Actions repository secret in Stage 10."
ask_secret BETTER_STACK_HEARTBEAT_URL "Paste the secret Better Stack heartbeat URL:"
require_https BETTER_STACK_HEARTBEAT_URL "$BETTER_STACK_HEARTBEAT_URL"
write_env BETTER_STACK_HEARTBEAT_URL "$BETTER_STACK_HEARTBEAT_URL"
pause "After the heartbeat is created and alert routing is tested, press Enter"
if ! confirm "Is Better Stack ready to receive the Preprod health heartbeat and alert on missed checks?"; then
  warn "Better Stack is not confirmed; stopping."
  exit 1
fi

stage "Configure the Vercel Preprod project"
say "Publish the browser-safe configuration for the checked-in apps/web build."
open_url "https://vercel.com/new"
open_url "https://vercel.com/docs/git"
open_url "https://vercel.com/docs/environment-variables/managing-environment-variables"
open_url "https://vercel.com/docs/project-configuration/project-settings"
step "Import the current $REPO_SLUG repository and configure the project root, build command, and output directory to match the committed apps/web/vercel.json and the monorepo's current build behavior. Confirm the resulting build profile rather than assuming a dashboard default."
step "Add the public variables below to the Preproduction target in Vercel, then redeploy after saving. The wizard writes the same values to ENV_FILE but does not use the Vercel CLI."
note "Captured values are public browser configuration. Source: the deployment worksheet, Midnight Preprod endpoints, Render, and the contract build/deployment outputs. Destination: ENV_FILE and Vercel environment variables; none are secrets."
ask VITE_SHROUDLY_DEPLOYMENT_ID "Paste the immutable Preprod deployment ID:"
require_value VITE_SHROUDLY_DEPLOYMENT_ID "$VITE_SHROUDLY_DEPLOYMENT_ID"
VITE_SHROUDLY_RPC_URL="https://rpc.preprod.midnight.network"
VITE_SHROUDLY_INDEXER_URL="https://indexer.preprod.midnight.network/api/v4/graphql"
write_env VITE_SHROUDLY_RPC_URL "$VITE_SHROUDLY_RPC_URL"
write_env VITE_SHROUDLY_INDEXER_URL "$VITE_SHROUDLY_INDEXER_URL"
ask VITE_SHROUDLY_ZK_CONFIG_URL "Paste the pinned ZK configuration URL:"
require_https VITE_SHROUDLY_ZK_CONFIG_URL "$VITE_SHROUDLY_ZK_CONFIG_URL"
ask VITE_SHROUDLY_SPONSOR_URL "Paste the public Sponsor Service URL:"
require_https VITE_SHROUDLY_SPONSOR_URL "$VITE_SHROUDLY_SPONSOR_URL"
ask VITE_SHROUDLY_ASSET_CONTRACT_ID "Paste the public TmixAsset contract ID:"
ask VITE_SHROUDLY_RANDOMNESS_CONTRACT_ID "Paste the public RandomnessThreshold contract ID:"
ask VITE_SHROUDLY_YIELD_CONTRACT_ID "Paste the public YieldAdapter contract ID:"
ask VITE_SHROUDLY_POOL_CONTRACT_ID "Paste the public PrizePool contract ID:"
require_value VITE_SHROUDLY_ASSET_CONTRACT_ID "$VITE_SHROUDLY_ASSET_CONTRACT_ID"
require_value VITE_SHROUDLY_RANDOMNESS_CONTRACT_ID "$VITE_SHROUDLY_RANDOMNESS_CONTRACT_ID"
require_value VITE_SHROUDLY_YIELD_CONTRACT_ID "$VITE_SHROUDLY_YIELD_CONTRACT_ID"
require_value VITE_SHROUDLY_POOL_CONTRACT_ID "$VITE_SHROUDLY_POOL_CONTRACT_ID"
ask VITE_SHROUDLY_ASSET_ARTIFACT_HASH "Paste the TmixAsset artifact hash:"
ask VITE_SHROUDLY_RANDOMNESS_ARTIFACT_HASH "Paste the RandomnessThreshold artifact hash:"
ask VITE_SHROUDLY_YIELD_ARTIFACT_HASH "Paste the YieldAdapter artifact hash:"
ask VITE_SHROUDLY_POOL_ARTIFACT_HASH "Paste the PrizePool artifact hash:"
require_hash VITE_SHROUDLY_ASSET_ARTIFACT_HASH "$VITE_SHROUDLY_ASSET_ARTIFACT_HASH"
require_hash VITE_SHROUDLY_RANDOMNESS_ARTIFACT_HASH "$VITE_SHROUDLY_RANDOMNESS_ARTIFACT_HASH"
require_hash VITE_SHROUDLY_YIELD_ARTIFACT_HASH "$VITE_SHROUDLY_YIELD_ARTIFACT_HASH"
require_hash VITE_SHROUDLY_POOL_ARTIFACT_HASH "$VITE_SHROUDLY_POOL_ARTIFACT_HASH"
write_env VITE_SHROUDLY_DEPLOYMENT_ID "$VITE_SHROUDLY_DEPLOYMENT_ID"
write_env VITE_SHROUDLY_ZK_CONFIG_URL "$VITE_SHROUDLY_ZK_CONFIG_URL"
write_env VITE_SHROUDLY_SPONSOR_URL "$VITE_SHROUDLY_SPONSOR_URL"
write_env VITE_SHROUDLY_ASSET_CONTRACT_ID "$VITE_SHROUDLY_ASSET_CONTRACT_ID"
write_env VITE_SHROUDLY_RANDOMNESS_CONTRACT_ID "$VITE_SHROUDLY_RANDOMNESS_CONTRACT_ID"
write_env VITE_SHROUDLY_YIELD_CONTRACT_ID "$VITE_SHROUDLY_YIELD_CONTRACT_ID"
write_env VITE_SHROUDLY_POOL_CONTRACT_ID "$VITE_SHROUDLY_POOL_CONTRACT_ID"
write_env VITE_SHROUDLY_ASSET_ARTIFACT_HASH "$VITE_SHROUDLY_ASSET_ARTIFACT_HASH"
write_env VITE_SHROUDLY_RANDOMNESS_ARTIFACT_HASH "$VITE_SHROUDLY_RANDOMNESS_ARTIFACT_HASH"
write_env VITE_SHROUDLY_YIELD_ARTIFACT_HASH "$VITE_SHROUDLY_YIELD_ARTIFACT_HASH"
write_env VITE_SHROUDLY_POOL_ARTIFACT_HASH "$VITE_SHROUDLY_POOL_ARTIFACT_HASH"
pause "After Vercel has the public variables, the new deployment is live, and its build profile matches the worksheet, press Enter"
if ! confirm "Is the public Vercel Preprod build configured without any credentials or mainnet transaction switch?"; then
  warn "Vercel is not confirmed; stopping."
  exit 1
fi

stage "Configure GitHub Actions operations"
say "Populate the exact repository variables and secrets referenced by .github/workflows/preprod.yml."
open_url "$REPO_URL/settings/variables/actions"
open_url "$REPO_URL/settings/secrets/actions"
open_url "$REPO_URL/actions/workflows/preprod.yml"
step "The workflow's randomness job must expose only SHROUDLY_GITHUB_ACTIONS_SEED, SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT, and SHROUDLY_GITHUB_ACTIONS_AUTOMATION_TOKEN. Render and offline-maintainer credentials stay in their own isolated runners and are never copied into GitHub Actions."
if ! confirm "Has the workflow/script credential contract been reviewed so each runner receives only its contributor-scoped seed and endpoint/token?"; then
  warn "GitHub operations remain blocked until credential isolation is confirmed."
  exit 1
fi
note "The names below are copied exactly from the current workflow. Values are written only after the confirmation below; no wallet keys or non-GitHub contributor credentials are captured."
ask SHROUDLY_DEPLOYMENT_ID "Paste the immutable deployment ID for the Actions variable:"
require_value SHROUDLY_DEPLOYMENT_ID "$SHROUDLY_DEPLOYMENT_ID"
ask SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT "Paste the HTTPS GitHub Actions automation endpoint for the Actions variable:"
require_https SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT "$SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT"
ask_secret BETTER_STACK_HEARTBEAT_URL "Paste the Better Stack heartbeat URL for the Actions secret:"
require_https BETTER_STACK_HEARTBEAT_URL "$BETTER_STACK_HEARTBEAT_URL"
ask_secret SHROUDLY_GITHUB_ACTIONS_SEED "Paste the isolated GitHub Actions contributor seed:"
require_value SHROUDLY_GITHUB_ACTIONS_SEED "$SHROUDLY_GITHUB_ACTIONS_SEED"
ask_secret SHROUDLY_GITHUB_ACTIONS_AUTOMATION_TOKEN "Paste the isolated GitHub Actions automation bearer token:"
require_value SHROUDLY_GITHUB_ACTIONS_AUTOMATION_TOKEN "$SHROUDLY_GITHUB_ACTIONS_AUTOMATION_TOKEN"
if ! confirm "Write the two GitHub Actions variables and three repository secrets now?"; then
  warn "GitHub values were not written; stopping before qualification."
  exit 1
fi
write_env BETTER_STACK_HEARTBEAT_URL "$BETTER_STACK_HEARTBEAT_URL"
write_env SHROUDLY_DEPLOYMENT_ID "$SHROUDLY_DEPLOYMENT_ID"
write_env SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT "$SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT"
set_var SHROUDLY_DEPLOYMENT_ID "$SHROUDLY_DEPLOYMENT_ID"
set_var SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT "$SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT"
set_secret BETTER_STACK_HEARTBEAT_URL "$BETTER_STACK_HEARTBEAT_URL"
set_secret SHROUDLY_GITHUB_ACTIONS_SEED "$SHROUDLY_GITHUB_ACTIONS_SEED"
set_secret SHROUDLY_GITHUB_ACTIONS_AUTOMATION_TOKEN "$SHROUDLY_GITHUB_ACTIONS_AUTOMATION_TOKEN"
note "GitHub Actions variables attempted: SHROUDLY_DEPLOYMENT_ID SHROUDLY_GITHUB_ACTIONS_AUTOMATION_ENDPOINT"

stage "Run Recovery Kit and Backup Account drills"
say "Prove recoverability before any qualifying contribution."
open_url "$REPO_URL/actions/workflows/preprod.yml"
open_url "https://vercel.com/dashboard"
note "Captured value: PREPROD_URL. Source: the live Vercel deployment. Destination: memory for this run only; it is not written to ENV_FILE, GitHub, or evidence."
ask PREPROD_URL "Paste the live Vercel Preprod URL for the drill:"
require_https PREPROD_URL "$PREPROD_URL"
open_url "$PREPROD_URL"
step "Export and restore a Recovery Kit for each participant wallet before its first contribution. Verify the restored wallet identity without exposing the kit to the wizard."
step "Run the Backup Account export/restore drill through the deployed app with the required AAL2 session. Confirm Supabase stores ciphertext only and retired/invalid restores are rejected."
step "Record only sanitized drill results and checksums in the protected evidence workspace."
pause "After both Recovery Kit and Backup Account drills pass, press Enter"
if ! confirm "Did Recovery Kit restore and Backup Account recovery pass with invalid/retired restore paths rejected?"; then
  warn "Recovery drills are not confirmed; stopping."
  exit 1
fi

stage "Perform the supported desktop Chrome/Lace transaction"
say "Use the genuine DApp Connector path from the public Vercel build."
open_url "$PREPROD_URL"
open_url "https://docs.midnight.network/api-reference/dapp-connector"
step "Use a supported desktop Chrome session with the correct Preprod Lace wallet. Do not use mobile or an unsupported browser for qualification."
step "Connect Lace, complete one minimal transaction from the public build, and record only the sanitized transaction reference."
step "Accept success only after network finality, indexer visibility, and a fresh ledger confirmation. Do not paste addresses, commitments, nullifiers, or private state here."
pause "After the Lace transaction is finalized and cross-checked, press Enter"
if ! confirm "Did the public build complete one genuine Lace transaction with finality, indexer, and ledger confirmation?"; then
  warn "Browser evidence is not confirmed; stopping."
  exit 1
fi

stage "Run the genuine five-wallet qualification draw"
say "Exercise the actual contribution, draw, and claim path with isolated wallets."
open_url "$PREPROD_URL"
open_url "$REPO_URL/issues/18"
step "Use four isolated setup wallets for qualifying contributions and the fifth as the primary browser wallet. Complete the real draw phases and deadlines."
step "Let the contract select the owner; the selected wallet alone may claim. Do not retry a winner, override selection, or substitute a deterministic fixture for this qualification."
step "For each transaction, retain only the required JSON flags: transactionId, networkFinalized, indexerVisible, ledgerConfirmed, deploymentId, and sourceRevision."
pause "After the five-wallet draw and selected-wallet claim have finalized, press Enter"
if ! confirm "Did the genuine five-wallet draw select an owner and allow only the selected wallet to claim?"; then
  warn "Five-wallet qualification is not confirmed; stopping."
  exit 1
fi

stage "Review and retain the sanitized evidence bundle"
say "Review evidence only after the qualification transactions are final and cross-checked."
open_url "$REPO_URL/actions/workflows/preprod.yml"
open_url "$REPO_URL/issues/18"
step "Dispatch the evidence operation only after health is green, then verify the bundle with scripts/verify-evidence.mjs."
step "Check that every transaction has finality, indexer, fresh-ledger, deployment, and source-revision fields. Scrub wallet addresses, commitments, nullifiers, backup IDs, private state, and secrets."
step "Retain the redacted/checksummed artifact in GitHub Actions for at least 90 days, and record the artifact/run reference in the release worksheet."
pause "After the evidence bundle is verified, redacted, checksummed, and retained, press Enter"
if ! confirm "Has the evidence review passed and is the 90-day Actions artifact retention confirmed?"; then
  warn "Evidence retention is not confirmed; stopping."
  exit 1
fi

stage "Complete governance handoff and remove temporary authority"
say "Perform the irreversible authority handoff only after all qualification evidence is accepted."
open_url "$REPO_URL/issues/18"
step "Use the approved two-of-three governance procedure to hand off operational authority, validate offline governance/emergency/randomness materials, and record only sanitized references."
step "Remove the Temporary Deployer Authority within 24 hours of final deployment. If removal cannot be finalized, lock submissions and follow the incident/governance procedure; never bypass the invariant."
warn "The repository does not define a human-safe handoff command. Use the reviewed protected operator procedure and verify the resulting state through finality, indexer, and ledger checks."
pause "After governance handoff and deployer removal have been finalized, press Enter"
if ! confirm "Is governance in control, are offline materials validated, and is Temporary Deployer Authority removed or the submission lock active?"; then
  warn "Governance handoff is not confirmed; stopping."
  exit 1
fi

stage "Create the immutable tag and GitHub Release"
say "Publish only after the release gates and evidence bundle have been reviewed."
open_url "$REPO_URL/issues/2"
open_url "$REPO_URL/issues/18"
open_url "$REPO_URL/releases/new"
step "Confirm the exact Compatibility Profile, source revision, deployment ID, four contract IDs/hashes, finalized evidence, provider approvals, and 90-day artifact retention."
step "Confirm Mainnet transactional entrypoints remain disabled and the published build is explicitly Preprod-only."
step "Create the immutable release tag and GitHub Release through the reviewed maintainer process, then close the completed human-gate child issues. Do not publish if any gate remains needs-info or ready-for-human."
pause "After the maintainer has created the immutable tag and GitHub Release, press Enter"
if ! confirm "Is the immutable release published with all human gates complete and Mainnet still disabled?"; then
  warn "Publication is not confirmed; stopping."
  exit 1
fi

finish
